[web]
${WEB_IP} ansible_user=ec2-user ansible_ssh_private_key_file=/home/vedant/my-tf-key.pem

[app]
${APP_IP} ansible_user=ec2-user ansible_ssh_private_key_file=/home/vedant/my-tf-key.pem

[app:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p ec2-user@${WEB_IP} -i /home/vedant/my-tf-key.pem"'
