writeFile file: "${ANSIBLE_DIR}/inventory.ini", text: """

[web]
${env.WEB_ID} ansible_connection=aws_ssm ansible_user=ec2-user ansible_python_interpreter=/home/vedant/ansible-venv/bin/python

[app]
${env.APP_ID} ansible_connection=aws_ssm ansible_user=ec2-user ansible_python_interpreter=/home/vedant/ansible-venv/bin/python
"""
