- name: Install Nginx on Web Tier
  hosts: web
  become: yes
  gather_facts: no

  tasks:

    - name: Install nginx
      dnf:
        name: nginx
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes


- name: Install MySQL on App Tier
  hosts: app
  become: yes
  gather_facts: no

  tasks:

    - name: Install MySQL server
      dnf:
        name: mysql-server
        state: present

    - name: Start MySQL
      service:
        name: mysqld
        state: started
        enabled: yes
