- hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: yes

- hosts: app
  become: yes
  tasks:
    - name: Install MySQL
      dnf:
        name: mysql-server
        state: present

    - name: Start MySQL
      service:
        name: mysqld
        state: started
        enabled: yes
